/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zavierdev.crudsiswa.ui.login;

import com.zavierdev.crudsiswa.auth.Session;
import com.zavierdev.crudsiswa.viewmodel.ViewModelConnectionObserver;
import com.zavierdev.crudsiswa.ui.home.HomeFrame;
import com.zavierdev.crudsiswa.utils.DialogBox;
import com.zavierdev.crudsiswa.utils.PasswordUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author tech
 */
public class LoginFrame extends javax.swing.JFrame {
    private LoginFrameViewModel loginFrameViewModel;
    
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        provideViewModel();
        initComponents();
        initShellActions();
        //generatePassword("mimin");
    }
    
    private void generatePassword(String password) {
        String securePassword;
        String salt;
        
        salt = PasswordUtils.getSalt(40);
        securePassword = PasswordUtils.generateSecurePassword(password, salt);
        
        System.out.println("Secure Password : "+securePassword);
        System.out.println("Salt            : "+salt);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblLogin.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblLogin.setText("Login");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(lblLogin)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogin)
                .addGap(47, 47, 47)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if(!validateLoginFormEmpty()) {
            String username = tfUsername.getText();
            String password = String.valueOf(tfPassword.getPassword());
            Session loginSession = loginFrameViewModel.performLogin(username, password);
            
            if(loginSession.getStatusLogin()) {
                startMainFrame(loginSession);
            } else {
                DialogBox.showMessageDialog(
                        "Maaf... \n"
                        + "Username atau Password Yang Anda Masukan Salah !");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void provideViewModel() {
        loginFrameViewModel = new LoginFrameViewModel();
    }
    
    private void initShellActions() {
        loginFrameViewModel.observeConnection(new ViewModelConnectionObserver() {
            @Override
            public void connectionStatus(boolean status) {
                if(!status) {
                    showDatabaseErrorDialog();
                }
            }
        });
    }
    
    private boolean validateLoginFormEmpty() {
        boolean isEmpty = false;
        
        if(tfUsername.getText().isEmpty()) {
            isEmpty = true;
            DialogBox.showMessageDialog("Silahkan isi username !");
        } else if(tfPassword.getPassword().length == 0) {
            isEmpty = true;
            DialogBox.showMessageDialog("Silahkan isi password !");
        }
        
        return isEmpty;
    }
    
    private void startMainFrame(Session session) {
        this.dispose();
        HomeFrame mainFrame = new HomeFrame(session);
    }
    
    private void showDatabaseErrorDialog() {
        int response = DialogBox.showOptionDialog(
                            "Error", 
                            "Database Gagal Terhubung !\nIngin Menyambungkannya Kembali ?",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.ERROR_MESSAGE);
            
        if(response == JOptionPane.YES_OPTION) {
            loginFrameViewModel.connectDB();
        } else {
            System.exit(0); // Exit Programs
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
